### ISSUE TITLE
is firebase use is paid plan.

### ISSUE THREAD

**Issue by Vishal18v** [Sharvin26/TodoApp#4]
the cloud deployment you have used, Is it paid firebase plan?
i was going line by line through your freecodecamp tutorial. it is showing for cloud deployment pay as go plan is required.

**Comment by mhgolestan** [comment]
@Vishal18v 
https://stackoverflow.com/questions/62852071/cloud-functions-deployment-requires-the-pay-as-you-go-blaze-billing-plan
