### ISSUE TITLE
Using both Firebase and Firebase ADMIN sdk in functions

### ISSUE THREAD

**Issue by vlitsolutions** [Sharvin26/TodoApp#5]
Hi,

First of all, I wanna say great project!

I was reading about firebase sdk and it seems that it is intended to be used on the frontend of the app. Is there any cons using both admin and normal firebase sdk on the functions server?

Since I intend to use it with redux as well, I want to know which way is the best: like yours, and use a simple reducer for auth state, or use signIn + react-redux-firebase on the frontend.

Thanks and keep up the good work! :)

**Comment by Sharvin26** [comment]
The reason I didn't use Firebase Library on the frontend side is that the firebase library increases the size of the application which inturns slowdowns the page loading time. So I preferred it using on the Backend. If you have any query reopen this issue.
